import React from 'react'
import Pixel from './Pixel'

const App = () => {
  return (
    <div className ="container">
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
      <Pixel /> 
    </div>
  )
}

export default App
